app:
  name: "chat-gateway"
  version: "1.0.0"
  debug: true

server:
  host: "0.0.0.0"
  port: "8080"
  timeout: 30
  use_https: false
  cert_path: ""
  key_path: ""

database:
  mongo:
    url: "mongodb://localhost:27017/chatroom"
    database: "chatroom"
    username: "devUser"
    password: "devPassword"
    max_pool_size: 100
    min_pool_size: 5
    max_conn_idle_time: 30
    connect_timeout: 10
    server_selection_timeout: 5

log:
  rotation_time_hours: 24
  max_age_days: 7
  max_size_mb: 100
