app:
  name: "chat-gateway"
  version: "1.0.0"
  debug: true

server:
  host: "localhost"
  port: "8080"
  timeout: 30
  use_https: false
  cert_path: ""
  key_path: ""

# air 本機開發專用配置
database:
  mongo:
    url: "mongodb://chat:1qaz@WSX@localhost:27017/chatroom?authSource=chatroom"
    database: "chatroom"
    username: ""
    password: ""
    # 連接池配置
    max_pool_size: 50 # 最大連接池大小
    min_pool_size: 5 # 最小連接池大小
    max_conn_idle_time: 30 # 連接最大閒置時間 (秒)
    connect_timeout: 10 # 連接超時 (秒)
    server_selection_timeout: 5 # 伺服器選擇超時 (秒)

log:
  rotation_time_hours: 24 # log rotation 時間 (小時)
  max_age_days: 7 # log 保留天數 (本地開發保留較短時間)
  max_size_mb: 50 # 單個 log 檔案最大大小 (MB)
